name: Build and Archive UserScript

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Check if artifact exists
        run: |
          if [ ! -f "dist/AnilistBytes.user.js" ]; then
            echo "Error: dist/AnilistBytes.user.js not found after build"
            exit 1
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: userscript
          path: dist/AnilistBytes.user.js
          retention-days: 30
